
import { Note } from "../types";

// Helper to generate an HTML-compatible Word document (MIME: application/msword)
export const exportToWord = (notes: Note[]) => {
  const content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>NEXO Notes</title>
      <style>
          body { font-family: 'Calibri', 'Arial', sans-serif; line-height: 1.5; }
          .note { margin-bottom: 30px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
          h1 { color: #2B6CFF; font-size: 24px; border-bottom: 1px solid #ccc; padding-bottom: 10px; }
          h2 { color: #333; font-size: 18px; margin-bottom: 5px; }
          .meta { color: #888; font-size: 12px; margin-bottom: 15px; }
          p { white-space: pre-wrap; }
      </style>
      </head><body>
      <h1>NEXO Archives Export</h1>
      ${notes.map(n => `
          <div class="note">
              <h2>${n.title}</h2>
              <div class="meta">
                  ID: ${n.id} | Created: ${new Date(n.createdAt).toLocaleString()} | Updated: ${new Date(n.updatedAt).toLocaleString()}
              </div>
              <p>${n.content.replace(/\n/g, '<br>')}</p>
          </div>
      `).join('')}
      <br>
      <p style="text-align: center; color: #aaa; font-size: 10px;">Generated by NEXO AI</p>
      </body></html>
  `;

  const blob = new Blob(['\ufeff', content], { type: 'application/msword' });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `nexo_notes_${new Date().toISOString().split('T')[0]}.doc`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Helper to trigger a print dialog for PDF saving
export const exportToPDF = (notes: Note[]) => {
    const printWindow = window.open('', '_blank');
    if(printWindow) {
        const content = `
            <html><head><title>NEXO Archives</title>
            <style>
                body{font-family:sans-serif;padding:40px;max-width:800px;margin:0 auto;} 
                .note{border-bottom:1px solid #ccc;padding:20px 0;page-break-inside: avoid;}
                h1{color:#000; border-bottom:2px solid #000; padding-bottom:10px;}
                h2{margin-bottom:5px;}
                .meta{font-size:12px;color:#666;margin-bottom:15px;}
                pre{white-space:pre-wrap;font-family:sans-serif;}
                @media print { button { display: none; } }
            </style>
            </head><body>
            <h1>NEXO Archives</h1>
            ${notes.map(n => `
                <div class="note">
                    <h2>${n.title}</h2>
                    <div class="meta">${new Date(n.createdAt).toLocaleString()}</div>
                    <pre>${n.content}</pre>
                </div>
            `).join('')}
            <script>
                window.onload = function() { window.print(); setTimeout(function(){ window.close(); }, 500); }
            </script>
            </body></html>
        `;
        printWindow.document.write(content);
        printWindow.document.close();
    }
};

export const exportNotes = async (
  notes: Note[], 
  format: string,
  notify?: (message: string, type: 'success' | 'info' | 'error') => void
) => {
  const fmt = format.toLowerCase();
  
  try {
    if (!notes || notes.length === 0) {
      throw new Error("No notes available to export.");
    }

    switch (fmt) {
      case 'docx':
      case 'word':
        exportToWord(notes);
        if (notify) notify("Archives exported to Word file.", 'success');
        break;
      case 'pdf':
        exportToPDF(notes);
        if (notify) notify("Opening Print Dialog. Choose 'Save as PDF'.", 'info');
        break;
      default:
        throw new Error(`Unsupported export format: ${format}. Only Word (docx) and PDF are supported.`);
    }
  } catch (error: any) {
    console.error("Export Error:", error);
    const errorMsg = error.message || "Export operation failed.";
    
    if (notify) {
      notify(errorMsg, 'error');
    } else {
      alert(errorMsg);
    }
    
    throw error;
  }
};
