import React, { useState } from "react";
import {
  X,
  ChevronRight,
  Settings,
  Download,
  MessageCircle,
  Rocket,
} from "lucide-react";
import { GithubIcon as Github } from "./GithubIcon";
import { useAgentStore } from "../../stores/agentStore";
import { useProjectStore } from "../../stores/projectStore";
import toast from "react-hot-toast";

interface SettingsModalProps {
  onClose: () => void;
  onDeploy: () => void;
  onLoadHistory: () => void;
  onDownloadZip: () => void;
  temperature: number;
  setTemperature: (t: number) => void;
  topP: number;
  setTopP: (t: number) => void;
  initialTab?: string;
}

export const SettingsModal: React.FC<SettingsModalProps> = ({
  onClose,
  onDeploy,
  onLoadHistory,
  onDownloadZip,
  temperature,
  setTemperature,
  topP,
  setTopP,
  initialTab,
}) => {
  const [activeTab, setActiveTab] = useState(initialTab === "Chat" ? "Models" : (initialTab || "Models"));
  const tabs = ["Models", "Share", "Publish", "Versions", "Integrations"];
  const { selectedModel, setSelectedModel } = useAgentStore();

  const [githubToken, setGithubToken] = useState(() => localStorage.getItem("nexo_gh_token") || "");
  const [repoUrl, setRepoUrl] = useState(() => localStorage.getItem("nexo_gh_repo") || "");
  const [commitMessage, setCommitMessage] = useState("Update from Nexo");
  const [branchName, setBranchName] = useState(() => localStorage.getItem("nexo_gh_branch") || "main");

  React.useEffect(() => {
    localStorage.setItem("nexo_gh_token", githubToken);
  }, [githubToken]);

  React.useEffect(() => {
    localStorage.setItem("nexo_gh_repo", repoUrl);
  }, [repoUrl]);

  React.useEffect(() => {
    localStorage.setItem("nexo_gh_branch", branchName);
  }, [branchName]);

  const [newRepoName, setNewRepoName] = useState("");
  const [isPrivateRepo, setIsPrivateRepo] = useState(true);
  const [prTitle, setPrTitle] = useState("Feature: UI update");
  const [prBody, setPrBody] = useState("Generated by Nexo AI Assistant.");
  const [prSourceBranch, setPrSourceBranch] = useState("feature-branch");
  const [prTargetBranch, setPrTargetBranch] = useState("main");
  const [prList, setPrList] = useState<any[]>([]);

  const handleCreateRepo = async () => {
    if (!githubToken || !newRepoName) {
      toast.error("Please provide GitHub token and Repository name.");
      return;
    }
    const files = useProjectStore.getState().currentContent?.files;
    if (!files || Object.keys(files).length === 0) {
      toast.error("No project files generated yet. Build a project first.");
      return;
    }
    const loadingToast = toast.loading("Creating repository...");
    try {
      const headers = {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      };
      const createRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers,
        body: JSON.stringify({
          name: newRepoName,
          private: isPrivateRepo,
          auto_init: true,
        }),
      });
      if (!createRes.ok) {
        const err = await createRes.json();
        throw new Error(err.message || "Failed to create repository.");
      }
      const repoData = await createRes.json();
      const newRepoUrl = repoData.html_url;
      setRepoUrl(newRepoUrl);
      localStorage.setItem("nexo_gh_repo", newRepoUrl);
      toast.dismiss(loadingToast);
      toast.success(`Repository created: ${newRepoName}`);

      toast.loading("Provisioning repository commits...");
      await new Promise(r => setTimeout(r, 3000));
      
      const owner = repoData.owner.login;
      const repoName = repoData.name;
      
      const refRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`,
        { headers },
      );
      if (!refRes.ok) throw new Error("Could not fetch main branch reference.");
      const refData = await refRes.json();
      const latestCommitSha = refData.object.sha;

      const commitRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/commits/${latestCommitSha}`,
        { headers },
      );
      const commitData = await commitRes.json();
      const baseTreeSha = commitData.tree.sha;

      const tree = Object.entries(files).map(([path, content]) => ({
        path: path.startsWith("/") ? path.slice(1) : path,
        mode: "100644",
        type: "blob",
        content,
      }));

      const newTreeRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/trees`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({ base_tree: baseTreeSha, tree }),
        },
      );
      if (!newTreeRes.ok) throw new Error("Failed to create Git tree.");
      const newTreeData = await newTreeRes.json();
      const newTreeSha = newTreeData.sha;

      const newCommitRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/commits`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            message: "Initial commit from NEXO Workspace",
            tree: newTreeSha,
            parents: [latestCommitSha],
          }),
        },
      );
      if (!newCommitRes.ok) throw new Error("Failed to create commit.");
      const newCommitData = await newCommitRes.json();
      const newCommitSha = newCommitData.sha;

      const updateRefRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`,
        {
          method: "PATCH",
          headers,
          body: JSON.stringify({ sha: newCommitSha }),
        },
      );
      if (!updateRefRes.ok) throw new Error("Failed to update branch reference.");

      toast.dismiss();
      toast.success("Project pushed successfully to the new repository!");
    } catch (e: any) {
      toast.dismiss();
      toast.error(e.message || "Failed to create repo or push.");
    }
  };

  const handleCreatePR = async () => {
    if (!githubToken || !repoUrl) {
      toast.error("GitHub credentials or repo configuration missing.");
      return;
    }
    const repoMatch = repoUrl.match(/github\.com\/([^\/]+)\/([^\/]+)/);
    if (!repoMatch) {
      toast.error("Invalid GitHub URL format.");
      return;
    }
    const owner = repoMatch[1];
    const repo = repoMatch[2].replace(/\.git$/, "");
    const loadingToast = toast.loading("Creating Pull Request...");
    try {
      const headers = {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      };
      const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          title: prTitle,
          body: prBody,
          head: prSourceBranch,
          base: prTargetBranch,
        }),
      });
      if (!prRes.ok) {
        const err = await prRes.json();
        throw new Error(err.message || "Failed to create PR.");
      }
      const prData = await prRes.json();
      toast.dismiss(loadingToast);
      toast.success(`PR Created: #${prData.number}`);
      fetchPRs();
    } catch (e: any) {
      toast.dismiss(loadingToast);
      toast.error(e.message || "PR creation failed.");
    }
  };

  const fetchPRs = async () => {
    if (!githubToken || !repoUrl) return;
    const repoMatch = repoUrl.match(/github\.com\/([^\/]+)\/([^\/]+)/);
    if (!repoMatch) return;
    const owner = repoMatch[1];
    const repo = repoMatch[2].replace(/\.git$/, "");
    try {
      const headers = {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github.v3+json",
      };
      const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls?state=all`, { headers });
      if (res.ok) {
        const data = await res.json();
        setPrList(data);
      }
    } catch (e) {}
  };

  React.useEffect(() => {
    if (activeTab === "Integrations" && githubToken && repoUrl) {
      fetchPRs();
    }
  }, [activeTab, githubToken, repoUrl]);

  const handleGithubPush = async () => {
    if (!githubToken || !repoUrl || !commitMessage) {
      toast.error("Please fill all required GitHub fields.");
      return;
    }

    const files = useProjectStore.getState().currentContent?.files;
    if (!files || Object.keys(files).length === 0) {
      toast.error("No files available to push. Build a project first.");
      return;
    }

    const repoMatch = repoUrl.match(/github\.com\/([^\/]+)\/([^\/]+)/);
    if (!repoMatch) {
      toast.error("Invalid GitHub URL format.");
      return;
    }
    const owner = repoMatch[1];
    const repo = repoMatch[2].replace(/\.git$/, "");

    const loadingToast = toast.loading("Pushing to GitHub...");

    try {
      const headers = {
        Authorization: `Bearer ${githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      };

      // 1. Get branch reference
      const refRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branchName}`,
        { headers },
      );
      if (!refRes.ok)
        throw new Error("Branch not found or token lacks access.");
      const refData = await refRes.json();
      const latestCommitSha = refData.object.sha;

      // 2. Get latest commit tree
      const commitRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/commits/${latestCommitSha}`,
        { headers },
      );
      const commitData = await commitRes.json();
      const baseTreeSha = commitData.tree.sha;

      // 3. Create new tree
      const tree = Object.entries(files).map(([path, content]) => ({
        path: path.startsWith("/") ? path.slice(1) : path,
        mode: "100644",
        type: "blob",
        content,
      }));

      const newTreeRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/trees`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({ base_tree: baseTreeSha, tree }),
        },
      );
      if (!newTreeRes.ok) throw new Error("Failed to create Git tree.");
      const newTreeData = await newTreeRes.json();
      const newTreeSha = newTreeData.sha;

      // 4. Create new commit
      const newCommitRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/commits`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            message: commitMessage,
            tree: newTreeSha,
            parents: [latestCommitSha],
          }),
        },
      );
      if (!newCommitRes.ok) throw new Error("Failed to create commit.");
      const newCommitData = await newCommitRes.json();
      const newCommitSha = newCommitData.sha;

      // 5. Update branch ref
      const updateRefRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branchName}`,
        {
          method: "PATCH",
          headers,
          body: JSON.stringify({ sha: newCommitSha }),
        },
      );
      if (!updateRefRes.ok)
        throw new Error("Failed to update branch reference.");

      toast.dismiss(loadingToast);
      toast.success("Successfully committed and pushed to GitHub!");
      setCommitMessage("");
    } catch (error: any) {
      toast.dismiss(loadingToast);
      toast.error(error.message || "An error occurred while pushing.");
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/20 backdrop-blur-sm animate-in fade-in duration-200 p-4">
      <div className="bg-white shadow-2xl w-full max-w-2xl h-[80vh] flex flex-col rounded-2xl overflow-hidden border border-stone-200 animate-in zoom-in-95 duration-300">
        {/* Tabs Header */}
        <div className="flex items-center justify-between border-b border-stone-100 px-3 py-2">
          <div className="flex items-center gap-1.5 overflow-x-auto no-scrollbar">
            {tabs.map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap transition-colors border ${activeTab === tab ? "bg-white text-stone-900 border-stone-200 shadow-sm" : "text-stone-600 hover:bg-stone-50 border-transparent hover:border-stone-200"}`}
              >
                {activeTab === tab && (
                  <span className="mr-1.5 inline-block w-1.5 h-1.5 bg-stone-800 rounded-full"></span>
                )}
                {tab}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-2 pl-2">
            <button className="p-2 hover:bg-stone-100 rounded-full transition-colors text-stone-400">
              <ChevronRight className="w-5 h-5" />
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-stone-100 rounded-full transition-colors shrink-0"
            >
              <X className="w-5 h-5 text-stone-500" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 md:p-10 bg-white">
          {activeTab === "Models" && (
            <div className="max-w-2xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-300">
              <div>
                <h2 className="text-xl font-bold text-stone-800 mb-1">
                  Model Marketplace &amp; Routing
                </h2>
                <p className="text-xs text-stone-500">
                  Select and configure the AI model that powers your editor session.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {[
                  {
                    id: "gemini-2.5-flash",
                    name: "Gemini 2.5 Flash",
                    provider: "Google AI",
                    desc: "Fast reasoning, high quota (Recommended)",
                    badge: "Free / Recommended",
                    badgeColor: "bg-emerald-50 text-emerald-700 border-emerald-100",
                    speed: "Fast (120+ t/s)",
                    cost: "$0.075 / 1M input"
                  },
                  {
                    id: "gemini-2.5-pro",
                    name: "Gemini 2.5 Pro",
                    provider: "Google AI",
                    desc: "Best quality, deep multi-step reasoning",
                    badge: "Pro Engine",
                    badgeColor: "bg-indigo-50 text-indigo-700 border-indigo-100",
                    speed: "Balanced (50 t/s)",
                    cost: "$1.25 / 1M input"
                  },
                  {
                    id: "gemini-2.0-flash",
                    name: "Gemini 2.0 Flash",
                    provider: "Google AI",
                    desc: "Balanced speed, latency & quality",
                    badge: "Stable",
                    badgeColor: "bg-blue-50 text-blue-700 border-blue-100",
                    speed: "Fast (100 t/s)",
                    cost: "$0.075 / 1M input"
                  },
                  {
                    id: "qwen/qwen3-coder-480b-a35b-instruct",
                    name: "Qwen 3 Coder 480B",
                    provider: "NVIDIA NIM",
                    desc: "State-of-the-art coding and complex planning",
                    badge: "NVIDIA NIM",
                    badgeColor: "bg-purple-50 text-purple-700 border-purple-100",
                    speed: "Moderate (30 t/s)",
                    cost: "$0.30 / 1M input"
                  },
                  {
                    id: "stepfun-ai/step-3.5-flash",
                    name: "Step 3.5 Flash",
                    provider: "NVIDIA NIM",
                    desc: "High speed reasoning and structured files",
                    badge: "NVIDIA NIM",
                    badgeColor: "bg-purple-50 text-purple-700 border-purple-100",
                    speed: "Fast (90 t/s)",
                    cost: "$0.10 / 1M input"
                  },
                  {
                    id: "groq/llama-3.3-70b-versatile",
                    name: "Llama 3.3 70B",
                    provider: "Groq Cloud",
                    desc: "High performance open source reasoning",
                    badge: "Groq API",
                    badgeColor: "bg-amber-50 text-amber-700 border-amber-100",
                    speed: "Ultra Fast (150+ t/s)",
                    cost: "$0.59 / 1M input"
                  }
                ].map((m) => (
                  <div
                    key={m.id}
                    onClick={() => setSelectedModel(m.id)}
                    className={`p-5 rounded-2xl border text-left cursor-pointer transition-all duration-300 relative group flex flex-col justify-between h-48 hover:shadow-md ${
                      selectedModel === m.id
                        ? "bg-stone-900 border-stone-900 text-white shadow-lg"
                        : "bg-white border-stone-200 text-stone-800 hover:border-stone-400"
                    }`}
                  >
                    <div>
                      <div className="flex items-start justify-between gap-2 mb-2">
                        <div>
                          <span className={`text-[9px] font-black uppercase tracking-wider block ${selectedModel === m.id ? "text-stone-400" : "text-stone-500"}`}>
                            {m.provider}
                          </span>
                          <h4 className="text-sm font-black tracking-tight">{m.name}</h4>
                        </div>
                        <span className={`text-[8px] font-black px-2 py-0.5 rounded-full border uppercase tracking-wider ${selectedModel === m.id ? "bg-white/10 text-white border-white/20" : m.badgeColor}`}>
                          {m.badge}
                        </span>
                      </div>
                      <p className={`text-[11px] leading-relaxed line-clamp-2 ${selectedModel === m.id ? "text-stone-300" : "text-stone-500"}`}>
                        {m.desc}
                      </p>
                    </div>

                    <div className="flex items-center justify-between border-t pt-3 border-dashed border-stone-700 mt-2 text-[10px] font-semibold text-stone-400">
                      <span>Speed: {m.speed}</span>
                      <span>Cost: {m.cost}</span>
                    </div>
                  </div>
                ))}
              </div>

              <div className="h-px w-full bg-stone-100"></div>

              {/* Advanced controls */}
              <div className="grid grid-cols-2 gap-6 bg-stone-50/50 p-5 rounded-2xl border border-stone-200/60">
                <div className="space-y-2">
                  <label className="block text-xs font-bold text-stone-600 uppercase tracking-widest">
                    Temperature: {temperature}
                  </label>
                  <input
                    type="range"
                    min="0"
                    max="1.5"
                    step="0.1"
                    value={temperature}
                    onChange={(e) => setTemperature(parseFloat(e.target.value))}
                    className="w-full h-1 bg-stone-200 rounded-lg appearance-none cursor-pointer accent-stone-800"
                  />
                </div>
                <div className="space-y-2">
                  <label className="block text-xs font-bold text-stone-600 uppercase tracking-widest">
                    Top P: {topP}
                  </label>
                  <input
                    type="range"
                    min="0.1"
                    max="1.0"
                    step="0.05"
                    value={topP}
                    onChange={(e) => setTopP(parseFloat(e.target.value))}
                    className="w-full h-1 bg-stone-200 rounded-lg appearance-none cursor-pointer accent-stone-800"
                  />
                </div>
              </div>
            </div>
          )}

          {activeTab === "Integrations" && (
            <div className="max-w-xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-300">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-stone-100 rounded-xl flex items-center justify-center">
                  <Github className="w-6 h-6 text-stone-800" />
                </div>
                <div>
                  <h2 className="text-xl font-bold text-stone-800">
                    GitHub Integrations
                  </h2>
                  <p className="text-stone-500 text-sm">
                    Manage repositories, commit updates, and generate pull requests.
                  </p>
                </div>
              </div>

              {/* GitHub Credentials */}
              <div className="space-y-6 bg-stone-50/50 p-6 rounded-2xl border border-stone-200">
                <h3 className="text-sm font-bold text-stone-800 uppercase tracking-wider">GitHub Settings</h3>
                <div className="space-y-2">
                  <label className="block text-xs font-semibold text-stone-600">
                    GitHub Access Token
                  </label>
                  <input
                    type="password"
                    value={githubToken}
                    onChange={(e) => setGithubToken(e.target.value)}
                    placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
                    className="w-full bg-white border border-stone-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-stone-400 focus:ring-4 focus:ring-stone-100 transition-all"
                  />
                  <p className="text-[10px] text-stone-500">
                    Requires 'repo' scope. Stored locally in your browser.
                  </p>
                </div>

                <div className="space-y-2">
                  <label className="block text-xs font-semibold text-stone-600">
                    Repository URL
                  </label>
                  <input
                    type="text"
                    value={repoUrl}
                    onChange={(e) => setRepoUrl(e.target.value)}
                    placeholder="https://github.com/username/repo-name"
                    className="w-full bg-white border border-stone-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-stone-400 focus:ring-4 focus:ring-stone-100 transition-all"
                  />
                </div>

                <div className="flex gap-4">
                  <div className="space-y-2 flex-1">
                    <label className="block text-xs font-semibold text-stone-600">
                      Branch
                    </label>
                    <input
                      type="text"
                      value={branchName}
                      onChange={(e) => setBranchName(e.target.value)}
                      placeholder="main"
                      className="w-full bg-white border border-stone-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-stone-400 focus:ring-4 focus:ring-stone-100 transition-all"
                    />
                  </div>
                  <div className="space-y-2 flex-[2]">
                    <label className="block text-xs font-semibold text-stone-600">
                      Commit Message
                    </label>
                    <input
                      type="text"
                      value={commitMessage}
                      onChange={(e) => setCommitMessage(e.target.value)}
                      placeholder="Update components..."
                      className="w-full bg-white border border-stone-200 rounded-xl px-4 py-3 text-sm outline-none focus:border-stone-400 focus:ring-4 focus:ring-stone-100 transition-all"
                    />
                  </div>
                </div>

                <button
                  onClick={handleGithubPush}
                  className="w-full py-3.5 bg-stone-900 text-white rounded-xl font-medium hover:bg-black transition-colors shadow-lg shadow-stone-900/10 mt-4 flex items-center justify-center gap-2 active:scale-[0.98]"
                >
                  <Github className="w-4 h-4" /> Push Commit
                </button>
              </div>

              {/* Create Repository */}
              <div className="space-y-4 bg-stone-50/50 p-6 rounded-2xl border border-stone-200">
                <h3 className="text-sm font-bold text-stone-800 uppercase tracking-wider">Create New Repository</h3>
                <div className="space-y-2">
                  <label className="block text-xs font-semibold text-stone-600">Repository Name</label>
                  <input
                    type="text"
                    value={newRepoName}
                    onChange={(e) => setNewRepoName(e.target.value)}
                    placeholder="my-cool-ai-app"
                    className="w-full bg-white border border-stone-200 rounded-xl px-4 py-3 text-sm outline-none"
                  />
                </div>
                <div className="flex items-center gap-2 text-xs font-semibold text-stone-600">
                  <input
                    type="checkbox"
                    checked={isPrivateRepo}
                    onChange={(e) => setIsPrivateRepo(e.target.checked)}
                    className="rounded accent-stone-900"
                  />
                  <span>Private repository</span>
                </div>
                <button
                  onClick={handleCreateRepo}
                  className="w-full py-3 bg-white border border-stone-300 text-stone-850 hover:bg-stone-50 rounded-xl font-semibold transition-colors mt-2"
                >
                  Create &amp; Push Project
                </button>
              </div>

              {/* Pull Request generator */}
              <div className="space-y-4 bg-stone-50/50 p-6 rounded-2xl border border-stone-200">
                <h3 className="text-sm font-bold text-stone-800 uppercase tracking-wider">Generate Pull Request (PR)</h3>
                
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="block text-xs font-semibold text-stone-600">Source (Compare)</label>
                    <input
                      type="text"
                      value={prSourceBranch}
                      onChange={(e) => setPrSourceBranch(e.target.value)}
                      placeholder="feature-branch"
                      className="w-full bg-white border border-stone-200 rounded-xl px-4 py-2.5 text-xs outline-none"
                    />
                  </div>
                  <div className="space-y-2">
                    <label className="block text-xs font-semibold text-stone-600">Target (Base)</label>
                    <input
                      type="text"
                      value={prTargetBranch}
                      onChange={(e) => setPrTargetBranch(e.target.value)}
                      placeholder="main"
                      className="w-full bg-white border border-stone-200 rounded-xl px-4 py-2.5 text-xs outline-none"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <label className="block text-xs font-semibold text-stone-600">PR Title</label>
                  <input
                    type="text"
                    value={prTitle}
                    onChange={(e) => setPrTitle(e.target.value)}
                    placeholder="Implement new styling"
                    className="w-full bg-white border border-stone-200 rounded-xl px-4 py-2.5 text-xs outline-none"
                  />
                </div>

                <div className="space-y-2">
                  <label className="block text-xs font-semibold text-stone-600">PR Description</label>
                  <textarea
                    value={prBody}
                    onChange={(e) => setPrBody(e.target.value)}
                    rows={2}
                    className="w-full bg-white border border-stone-200 rounded-xl px-4 py-2 text-xs outline-none resize-none"
                  />
                </div>

                <button
                  onClick={handleCreatePR}
                  className="w-full py-3 bg-indigo-650 text-white bg-indigo-600 hover:bg-indigo-700 rounded-xl font-semibold transition-colors mt-2"
                >
                  Create Pull Request
                </button>
              </div>

              {/* PR List */}
              {prList.length > 0 && (
                <div className="space-y-4 bg-stone-50/50 p-6 rounded-2xl border border-stone-200">
                  <h3 className="text-xs font-bold text-stone-500 uppercase tracking-widest">Active Pull Requests</h3>
                  <div className="space-y-2 divide-y divide-stone-200/60 max-h-48 overflow-y-auto no-scrollbar">
                    {prList.map((pr: any) => (
                      <div key={pr.id} className="pt-3 first:pt-0 flex items-center justify-between text-xs">
                        <div>
                          <span className="font-semibold text-stone-800">#{pr.number} {pr.title}</span>
                          <span className="text-[10px] text-stone-400 block">
                            State: <strong className={pr.state === "open" ? "text-emerald-600" : "text-stone-500"}>{pr.state}</strong> | Creator: {pr.user.login}
                          </span>
                        </div>
                        <a
                          href={pr.html_url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="px-3 py-1 bg-stone-100 border border-stone-200 rounded-lg hover:bg-stone-250 hover:text-black font-semibold text-stone-600"
                        >
                          View PR
                        </a>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Share & Publish tab stubs with old quick actions */}
          {["Share", "Publish", "Versions"].includes(activeTab) && (
            <div className="max-w-xl mx-auto h-full flex flex-col pt-8 animate-in fade-in duration-300">
              <h2 className="text-xl font-bold text-stone-800 mb-6">
                {activeTab}
              </h2>
              <p className="text-stone-500 mb-8">
                Quick actions for {activeTab.toLowerCase()} and deployment.
              </p>

              <div className="grid grid-cols-2 gap-4">
                <button
                  onClick={() => {
                    onClose();
                    onDeploy();
                  }}
                  className="flex flex-col items-center justify-center gap-3 p-6 bg-stone-50 hover:bg-stone-100 text-stone-700 rounded-2xl border border-stone-200 transition-all active:scale-[0.98]"
                >
                  <Rocket className="w-6 h-6" />
                  <span className="font-medium">Deploy Live</span>
                </button>
                <button
                  onClick={() => {
                    onClose();
                    onDownloadZip();
                  }}
                  className="flex flex-col items-center justify-center gap-3 p-6 bg-stone-50 hover:bg-stone-100 text-stone-700 rounded-2xl border border-stone-200 transition-all active:scale-[0.98]"
                >
                  <Download className="w-6 h-6" />
                  <span className="font-medium">Export ZIP</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
